### ISSUE TITLE
[Bug] PUT Update legal entity error

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/ehealth.api#102]
Error during update Legal Entity

` {
  "meta": {
    "url": "http://35.187.108.206/api/legal_entities",
    "type": "object",
    "request_id": "t0ijbkpmaieopublkt98hn9b7esp0tpf",
    "code": 422
  },
  "error": {
    "type": "validation_failed",
    "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
    "invalid": [
      {
        "rules": [
          {
            "rule": null,
            "params": [
            ],
            "description": "has already been taken"
          }
        ],
        "entry_type": "json_data_property",
        "entry": "$.edrpou"
      }
    ]
  }
}
`
[curl_update_legal_entity.txt](https://github.com/Nebo15/ehealth.api/files/972757/curl_update_legal_entity.txt)

**Comment by PavelVesnin** [comment]
It was invalid test data
