### ISSUE TITLE
Sensitive Data in the URL

### ISSUE THREAD

**Issue by DScheglov** [Nebo15/ehealth.api#11]
The sending search requests with sensitive personal data like as Name, TaxId and Birthday via the GET method is not safe. The URL is not encrypted even over HTTPS. So All requests with such kind of data should be sent via the POST method to ensure that this data is in the encrypted body.

Please consider: http://docs.ehealthapi1.apiary.io/#reference/private-master-patients-index/persons/search-for-a-patient

As a workaround the search-hashes could be used but it is some weird.

**Comment by AndrewDryga** [comment]
URL (and in this case query parameters) are encrypted over HTTPS (TLS/SSL) connection.

**Comment by DScheglov** [comment]
ok
