### ISSUE TITLE
[Address] add mountain_group

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#135]
Add mountain_group to the settlement entity - to keep the information about [mountain status](http://zakon2.rada.gov.ua/laws/show/647-95-п) of the settlement
[uaddress.txt](https://github.com/Nebo15/ehealth.api/files/995405/uaddress.txt)

`[settlements]`
`+ mountain_group | VARCHAR(150)`

**Comment by mmiliaieva** [comment]
now mountain_group in uaddresses db table settlements is boolean

**Comment by Samorai** [comment]
Field mountain_group was added as boolean type. 
I'll add it to the apiary in few minutes
@lymychp
