### ISSUE TITLE
Validate foreign keys on employee request

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/ehealth.api#154]
Validate foreign keys before create employee request:

- legal_entity_id
- division_id
- employee_id

Acceptance criteria:

1. Create employee request with invalid legal_entity_id or division_id or employee_id

- [ ] Validation error during create employee request
```
{
  "meta": {
    "url": "http://api-svc.il/api/employee_requests/fba77d7a-44bd-40a4-b557-ee0cf954d607/approve",
    "type": "object",
    "request_id": "9rj0shhb8tig80da4qokq1343pb8100d",
    "code": 422
  },
  "error": {
    "type": "validation_failed",
    "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
    "invalid": [
      {
        "rules": [
          {
            "rule": null,
            "params": [],
            "description": "does not exist"
          }
        ],
        "entry_type": "json_data_property",
        "entry": "$.legal_entity_id"
      }
    ]
  }
}
```
- [ ] No validation errors during approve employee request

**Comment by mmiliaieva** [comment]
If response contains invalid devision_id, service responds with 200. Validation doesn't work
Request example:
`{
  "employee_request": {
    "legal_entity_id": "65fb7776-a58f-4440-bea9-1281c8fa1723",
    "devision_id": "23fb7776-a58f-4440-bea9-1281c8fa1723",
    "position": "лікар",
    "start_date": "2017-03-02",
    "status": "NEW",
    "employee_type": "DOCTOR",
    "party": {
      "first_name": "Миколкака",
      "last_name": "Іванов",
      "second_name": "Миколайович",
      "birth_date": "1991-08-19",
      "gender": "MALE",
      "tax_id": "1226509812",
      "email": "m.miliaieva@gmail.com",
      "documents": [
        {
          "type": "PASSPORT",
          "number": "222518"
        }
      ],
      "phones": [
        {
          "type": "MOBILE",
          "number": "+380503410870"
        }
      ]
    },
    "doctor": {
      "educations": [
        {
          "country": "UA",
          "city": "Київ",
          "institution_name": "Академія Богомольця",
          "issued_date": "2017-08-05",
          "diploma_number": "DD123543",
          "degree": "Молодший спеціаліст",
          "speciality": "Педіатр"
        }
      ],
      "qualifications": [
        {
          "type": "Інтернатура",
          "institution_name": "Академія Богомольця",
          "speciality": "Педіатр",
          "issued_date": "2017-08-05",
          "certificate_number": "2017-08-05"
        }
      ],
      "specialities": [
        {
          "speciality": "Педіатр",
          "speciality_officio": true,
          "level": "Перша категорія",
          "qualification_type": "Присвоєння",
          "attestation_name": "Академія Богомольця",
          "attestation_date": "2017-08-05",
          "valid_to_date": "2017-08-05",
          "certificate_number": "AB/21331"
        }
      ],
      "science_degree": {
        "country": "UA",
        "city": "Київ",
        "degree": "Доктор філософії",
        "institution_name": "Академія Богомольця",
        "diploma_number": "DD123543",
        "speciality": "Педіатр",
        "issued_date": "2017-08-05"
      }
    }
  }
}
`
Response example:
`{
  "meta": {
    "url": "http://api-svc.il/api/employee_requests",
    "type": "object",
    "request_id": "u3gc7qcrhr33cl6ag9ae63rra2m46giq",
    "code": 200
  },
  "data": {
    "updated_at": "2017-05-23T11:08:46.232485",
    "status": "NEW",
    "start_date": "2017-03-02",
    "position": "лікар",
    "party": {
      "tax_id": "1226509812",
      "second_name": "Миколайович",
      "phones": [
        {
          "type": "MOBILE",
          "number": "+380503410870"
        }
      ],
      "last_name": "Іванов",
      "gender": "MALE",
      "first_name": "Миколкака",
      "email": "m.miliaieva@gmail.com",
      "documents": [
        {
          "type": "PASSPORT",
          "number": "222518"
        }
      ],
      "birth_date": "1991-08-19"
    },
    "legal_entity_id": "65fb7776-a58f-4440-bea9-1281c8fa1723",
    "inserted_at": "2017-05-23T11:08:46.232468",
    "id": "7ac0a438-ef12-4bf1-9049-b4a388eb756e",
    "employee_type": "DOCTOR",
    "doctor": {
      "specialities": [
        {
          "valid_to_date": "2017-08-05",
          "speciality_officio": true,
          "speciality": "Педіатр",
          "qualification_type": "Присвоєння",
          "level": "Перша категорія",
          "certificate_number": "AB/21331",
          "attestation_name": "Академія Богомольця",
          "attestation_date": "2017-08-05"
        }
      ],
      "science_degree": {
        "speciality": "Педіатр",
        "issued_date": "2017-08-05",
        "institution_name": "Академія Богомольця",
        "diploma_number": "DD123543",
        "degree": "Доктор філософії",
        "country": "UA",
        "city": "Київ"
      },
      "qualifications": [
        {
          "type": "Інтернатура",
          "speciality": "Педіатр",
          "issued_date": "2017-08-05",
          "institution_name": "Академія Богомольця",
          "certificate_number": "2017-08-05"
        }
      ],
      "educations": [
        {
          "speciality": "Педіатр",
          "issued_date": "2017-08-05",
          "institution_name": "Академія Богомольця",
          "diploma_number": "DD123543",
          "degree": "Молодший спеціаліст",
          "country": "UA",
          "city": "Київ"
        }
      ]
    },
    "devision_id": "23fb7776-a58f-4440-bea9-1281c8fa1723"
  }
}`
