### ISSUE TITLE
Release 01.06.17 preparation plan

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#164]
- [x] Configure dictionaries on the GW
- [x] fill-in dictionary values
- [ ] Approve global parameters @DPashchenko @itsyganok13 
- [ ] approve token lifetime with PO @gmile @itsyganok13 
  * access token - 1 day
  * refresh token - 1 month
- [x] import the region-district-settlement data to the uaddresses db #179  @AndrewDryga 
- [x] Configure uaddresses on the GW
- [x] deploy uadresses to demo cluster
- [x] add the dictionary validation #170 
- [x] stable build version @AlekzandrV 
- [x] deploy to the prod cluster @AndrewDryga 

Prod conf
- [x] import the dictionaries @AndrewDryga 
- [x] update dictionaries after approval  @AndrewDryga
- [x] import addresses data @AndrewDryga 
- [x] register MIS: legal_entity, client, user, scopes, token @gmile  
- [x] import roles to mithril @gmile 
- [x] configure client in mithril for FE @gmile 
- [x] import GW config @gmile 
- [x] import man template @AndrewDryga 
- [x] configure PROD approval link for employee request
- [x] google cloud storage config @AndrewDryga 
- [x] Set up Postmark prod account
- [x] MIS public API - support tickets.
- [x] register client for the auth
- [x] email domain name config
- [ ] import Ukraine_med_registry list
- [x] import digital sign certificates to demo @DPashchenko 
Misc.:
- [x] Notification after successful employee registration @lymychp 
- [ ] Approve mail text @alexeybondarenko  @itsyganok13 
- [ ] Approve front content @alexeybondarenko  @itsyganok13 

APIs to be delivered:

- [x] Create Legal Entity
- [x] Get Legal Entity list
- [x] Get Legal Entity by ID
- [x] Get Employee Request
- [x] Get UAdresses
- [x] Get dictionaries
- [x] auth
- [x] restrict access to all other endpoints @gmile

**Comment by AndrewDryga** [comment]
@lymychp I am not aware about this part of service: `register MIS: legal_entity, client, user, scopes, token`

**Comment by lymychp** [comment]
@AndrewDryga it means manual creation of MIS in Mithril
