### ISSUE TITLE
[IL] First legal_entity creation - 404 Error

### ISSUE THREAD

**Issue by mmiliaieva** [Nebo15/ehealth.api#176]
In case of creating a new legal_entity, service responds with 404 Error
Request example:
`{
"signed_legal_entity_request":"MIIX0gYJKoZIhvcNAQcCoIIXwzCCF78CAQExDjAMBgoqhiQCAQEBAQIBMIIIYAYJKoZIhvcNAQcBoIIIUQSCCE17DQogICJuYW1lIjogItCa0LvRltC90ZbQutCwINCQ0LTQvtC90ZbRgSIsDQogICJzaG9ydF9uYW1lIjogItCQ0LTQvtC90ZbRgSIsDQogICJwdWJsaWNfbmFtZSI6ICLQkNC00L7QvdGW0YEiLA0KICAidHlwZSI6ICJNU1AiLA0KICAib3duZXJfcHJvcGVydHlfdHlwZSI6ICJTVEFURSIsDQogICJsZWdhbF9mb3JtIjogItCf0IbQlNCf0KDQmNCE0JzQldCm0KwiLA0KICAiZWRycG91IjogIjM4NzgyMzIzIiwNCiAgImt2ZWRzIjogWw0KICAgICI4Ni4xMCINCiAgXSwNCiAgImFkZHJlc3NlcyI6IFsNCiAgICB7DQogICAgICAidHlwZSI6ICJSRVNJREVOQ0UiLA0KICAgICAgImNvdW50cnkiOiAiVUEiLA0KICAgICAgImFyZWEiOiAi0JbQuNGC0L7QvNC40YDRgdGM0LrQsCIsDQogICAgICAicmVnaW9uIjogItCR0LXRgNC00LjRh9GW0LLRgdGM0LrQuNC5IiwNCiAgICAgICJzZXR0bGVtZW50IjogItCa0LjRl9CyIiwNCiAgICAgICJzZXR0bGVtZW50X3R5cGUiOiAiQ0lUWSIsDQogICAgICAic2V0dGxlbWVudF9pZCI6ICI0MzQzMjQzMiIsDQogICAgICAic3RyZWV0X3R5cGUiOiAiU1RSRUVUIiwNCiAgICAgICJzdHJlZXQiOiAi0LLRg9C7LiDQndGW0LbQuNC90YHRjNC60LAiLA0KICAgICAgImJ1aWxkaW5nIjogIjE1IiwNCiAgICAgICJhcGFydG1lbnQiOiAiMjMiLA0KICAgICAgInppcCI6ICIwMjA5MCINCiAgICB9DQogIF0sDQogICJwaG9uZXMiOiBbDQogICAgew0KICAgICAgInR5cGUiOiAiTU9CSUxFIiwNCiAgICAgICJudW1iZXIiOiAiKzM4MDUwMzQxMDg3MCINCiAgICB9DQogIF0sDQogICJlbWFpbCI6ICJtLm1pbGlhaWV2YUBnbWFpbC5jb20iLA0KICAib3duZXIiOiB7DQogICAgImZpcnN0X25hbWUiOiAi0J/QtdGC0YDQviIsDQogICAgImxhc3RfbmFtZSI6ICLQhtCy0LDQvdC+0LIiLA0KICAgICJzZWNvbmRfbmFtZSI6ICLQnNC40LrQvtC70LDQudC+0LLQuNGHIiwNCiAgICAidGF4X2lkIjogIjMwMTU0OTI1NjUiLA0KICAgICJiaXJ0aF9kYXRlIjogIjE5OTEtMDgtMTkiLA0KICAgICJiaXJ0aF9wbGFjZSI6ICLQktGW0L3QvdC40YbRjywg0KPQutGA0LDRl9C90LAiLA0KICAgICJnZW5kZXIiOiAiTUFMRSIsDQogICAgImVtYWlsIjogIm0ubWlsaWFpZXZhQGdtYWlsLmNvbSIsDQogICAgImRvY3VtZW50cyI6IFsNCiAgICAgIHsNCiAgICAgICAgInR5cGUiOiAiUEFTU1BPUlQiLA0KICAgICAgICAibnVtYmVyIjogIjEyMDUxOCINCiAgICAgIH0NCiAgICBdLA0KICAgICJwaG9uZXMiOiBbDQogICAgICB7DQogICAgICAgICJ0eXBlIjogIk1PQklMRSIsDQogICAgICAgICJudW1iZXIiOiAiKzM4MDUwMzQxMDg3MCINCiAgICAgIH0NCiAgICBdLA0KICAgICJwb3NpdGlvbiI6ICLQk9C+0LvQvtCy0LAg0L/RgNCw0LLQu9GW0L3QvdGPIg0KICB9LA0KICAibWVkaWNhbF9zZXJ2aWNlX3Byb3ZpZGVyIjogew0KICAgICJsaWNlbnNlcyI6IFsNCiAgICAgIHsNCiAgICAgICAgImxpY2Vuc2VfbnVtYmVyIjogImZkMTIzNDQzIiwNCiAgICAgICAgImlzc3VlZF9ieSI6ICLQmtCy0LDQu9GW0YTRltC60LDRhtC50L3QsCDQutC+0LzRltGB0ZbRjyIsDQogICAgICAgICJpc3N1ZWRfZGF0ZSI6ICIxOTkxLTA4LTE5IiwNCiAgICAgICAgImV4cGlyeV9kYXRlIjogIjE5OTEtMDgtMTkiLA0KICAgICAgICAia3ZlZCI6ICI4Ni4xMCIsDQogICAgICAgICJ3aGF0X2xpY2Vuc2VkIjogItGA0LXQsNC70ZbQt9Cw0YbRltGPINC90LDRgNC60L7RgtC40YfQvdC40YUg0LfQsNGB0L7QsdGW0LIiDQogICAgICB9DQogICAgXSwNCiAgICAiYWNjcmVkaXRhdGlvbiI6IHsNCiAgICAgICJjYXRlZ29yeSI6ICLQn9CV0KDQqNCQIiwNCiAgICAgICJpc3N1ZWRfZGF0ZSI6ICIxOTkxLTA4LTE5IiwNCiAgICAgICJleHBpcnlfZGF0ZSI6ICIxOTkxLTA4LTE5IiwNCiAgICAgICJvcmRlcl9ubyI6ICJmZDEyMzQ0MyIsDQogICAgICAib3JkZXJfZGF0ZSI6ICIxOTkxLTA4LTE5Ig0KICAgIH0NCiAgfSwNCiAgInNlY3VyaXR5Ijogew0KICAgICJyZWRpcmVjdF91cmkiOiAicmVkaXJlY3RfdXJpIg0KICB9LA0KICAicHVibGljX29mZmVyIjogew0KICAgICJjb25zZW50IjogdHJ1ZSwNCiAgICAiY29uc2VudF90ZXh0IjogIkNvbnNlbnQgdGV4dCINCiAgfQ0KfQ0KoIIHLTCCBykwggbRoAMCAQICFDO2y3v3IbnOBAAAAH3DIQBJYU8AMA0GCyqGJAIBAQEBAwEBMIIBUDFUMFIGA1UECgxL0IbQvdGE0L7RgNC80LDRhtGW0LnQvdC+LdC00L7QstGW0LTQutC+0LLQuNC5INC00LXQv9Cw0YDRgtCw0LzQtdC90YIg0JTQpNChMV4wXAYDVQQLDFXQo9C/0YDQsNCy0LvRltC90L3RjyAo0YbQtdC90YLRgCkg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMWIwYAYDVQQDDFnQkNC60YDQtdC00LjRgtC+0LLQsNC90LjQuSDRhtC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTEUMBIGA1UEBQwLVUEtMzkzODQ0NzYxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsjAeFw0xNzAxMTcyMjAwMDBaFw0xOTAxMTcyMjAwMDBaMIHfMTwwOgYDVQQKDDPQotCe0JIgItCV0KTQhtCiINCi0JXQmtCd0J7Qm9Ce0JTQltCG0KEiICjQotCV0KHQoikxETAPBgNVBAsMCNCi0LXRgdGCMREwDwYDVQQMDAjRgtC10YHRgjEYMBYGA1UEAwwP0KLQtdGB0YIg0KIu0KIuMREwDwYDVQQEDAjQotC10YHRgjEaMBgGA1UEKgwR0KLQtdGB0YIg0KLQtdGB0YIxEDAOBgNVBAUMBzIyMTI3MzMxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsjCB8jCByQYLKoYkAgEBAQEDAQEwgbkwdTAHAgIBAQIBDAIBAAQhEL7j22rqnh+GV4xFwSWU/5QjlKfXOPkYfmUVAXKU9M4BAiEAgAAAAAAAAAAAAAAAAAAAAGdZITrxgumH0+F3FJB9Rw0EIbYP0tjc6Kk0I8YQG8qRxHoAfmwwCybNVWybDn0g7ykqAARAqdbrRfE8cIKAxJZ7Ix9erfZY66TANykdONlr8CXKThf46XINxhW0OiiXXwvB3qNkOLVk6iwXn9ASPm24+sV5BAMkAAQhkYNvax4g7+7gjfC/w8CpI10i4DC27IyspadzSpkDDSIAo4IDWDCCA1QwKQYDVR0OBCIEIFQvtE2mAXkJ7Pq0O3Bj8eE41vB5KnxW8qsFbbC0gQLCMCsGA1UdIwQkMCKAIDO2y3v3IbnO7uPeLmL+6jtwGktnYLwcL881ZRa1DryqMC8GA1UdEAQoMCagERgPMjAxNzAxMTcyMjAwMDBaoREYDzIwMTkwMTE3MjIwMDAwWjAOBgNVHQ8BAf8EBAMCBsAwGQYDVR0gAQH/BA8wDTALBgkqhiQCAQEBAgIwDAYDVR0TAQH/BAIwADAeBggrBgEFBQcBAwEB/wQPMA0wCwYJKoYkAgEBAQIBMIGnBgNVHREEgZ8wgZygTQYMKwYBBAGBl0YBAQQCoD0MOzA0MDg2LCDQvC4g0JrQuNGX0LIsINCy0YPQuy4g0J7Qu9C10L3QuCDQotC10LvRltCz0LgsIDM5LdCQoCYGDCsGAQQBgZdGAQEEAaAWDBQrMzggKDAgNDQpIDM4My0zMi0zN4EQaW5mb0BlZml0LmNvbS51YaARBgorBgEEAYI3FAIDoAMMATYwSAYDVR0fBEEwPzA9oDugOYY3aHR0cDovL2Fjc2tpZGQuZ292LnVhL2Rvd25sb2FkL2NybHMvQUNTS0lERERGUy1GdWxsLmNybDBJBgNVHS4EQjBAMD6gPKA6hjhodHRwOi8vYWNza2lkZC5nb3YudWEvZG93bmxvYWQvY3Jscy9BQ1NLSUREREZTLURlbHRhLmNybDCBiAYIKwYBBQUHAQEEfDB6MDAGCCsGAQUFBzABhiRodHRwOi8vYWNza2lkZC5nb3YudWEvc2VydmljZXMvb2NzcC8wRgYIKwYBBQUHMAKGOmh0dHA6Ly9hY3NraWRkLmdvdi51YS9kb3dubG9hZC9jZXJ0aWZpY2F0ZXMvYWxsYWNza2lkZC5wN2IwPwYIKwYBBQUHAQsEMzAxMC8GCCsGAQUFBzADhiNodHRwOi8vYWNza2lkZC5nb3YudWEvc2VydmljZXMvdHNwLzBlBgNVHQkEXjBcMBoGDCqGJAIBAQELAQQCATEKEwgzODc4MjMyMzAcBgwqhiQCAQEBCwEEAQExDBMKMTExMTExMTExMTAgBgwqhiQCAQEBCwEECwExEBMOMTk5MTA4MjQtMDAwMjYwDQYLKoYkAgEBAQEDAQEDQwAEQA0NJidk/creHhu1SQtcNDVSFWNwIjVejC0PT6Fffjc33F/BY6rfgb6FiU8CiCQ1KuOPx6t2gaH7Gm2f2q1SLxoxgggTMIIIDwIBATCCAWowggFQMVQwUgYDVQQKDEvQhtC90YTQvtGA0LzQsNGG0ZbQudC90L4t0LTQvtCy0ZbQtNC60L7QstC40Lkg0LTQtdC/0LDRgNGC0LDQvNC10L3RgiDQlNCk0KExXjBcBgNVBAsMVdCj0L/RgNCw0LLQu9GW0L3QvdGPICjRhtC10L3RgtGAKSDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExYjBgBgNVBAMMWdCQ0LrRgNC10LTQuNGC0L7QstCw0L3QuNC5INGG0LXQvdGC0YAg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMRQwEgYDVQQFDAtVQS0zOTM4NDQ3NjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyAhQztst79yG5zgQAAAB9wyEASWFPADAMBgoqhiQCAQEBAQIBoIIGOzAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xNzA1MTcxNDE1MDdaMC8GCSqGSIb3DQEJBDEiBCBo7grahr5uttsUJ3QzXR6V9el56qXCxd/l42u95lhomzCCAcMGCyqGSIb3DQEJEAIvMYIBsjCCAa4wggGqMIIBpjAMBgoqhiQCAQEBAQIBBCC7ccpmecfhw7lzChGDi5gR9BE0V/iKIh05UcNzJ/Jt0DCCAXIwggFYpIIBVDCCAVAxVDBSBgNVBAoMS9CG0L3RhNC+0YDQvNCw0YbRltC50L3Qvi3QtNC+0LLRltC00LrQvtCy0LjQuSDQtNC10L/QsNGA0YLQsNC80LXQvdGCINCU0KTQoTFeMFwGA1UECwxV0KPQv9GA0LDQstC70ZbQvdC90Y8gKNGG0LXQvdGC0YApINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTFiMGAGA1UEAwxZ0JDQutGA0LXQtNC40YLQvtCy0LDQvdC40Lkg0YbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExFDASBgNVBAUMC1VBLTM5Mzg0NDc2MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LICFDO2y3v3IbnOBAAAAH3DIQBJYU8AMIIEBwYLKoZIhvcNAQkQAhQxggP2MIID8gYJKoZIhvcNAQcCoIID4zCCA98CAQMxDjAMBgoqhiQCAQEBAQIBMGsGCyqGSIb3DQEJEAEEoFwEWjBYAgEBBgoqhiQCAQEBAgMBMDAwDAYKKoYkAgEBAQECAQQgaO4K2oa+brbbFCd0M10elfXpeeqlwsXf5eNrveZYaJsCBAIIlUoYDzIwMTcwNTE3MTQxNDU3WjGCA1swggNXAgEBMIIBEzCB+jE/MD0GA1UECgw20JzRltC90ZbRgdGC0LXRgNGB0YLQstC+INGO0YHRgtC40YbRltGXINCj0LrRgNCw0ZfQvdC4MTEwLwYDVQQLDCjQkNC00LzRltC90ZbRgdGC0YDQsNGC0L7RgCDQhtCi0KEg0KbQl9CeMUkwRwYDVQQDDEDQptC10L3RgtGA0LDQu9GM0L3QuNC5INC30LDRgdCy0ZbQtNGH0YPQstCw0LvRjNC90LjQuSDQvtGA0LPQsNC9MRkwFwYDVQQFDBBVQS0wMDAxNTYyMi0yMDEyMQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LICFDAEdR3vLHiuAgAAAAEAAABOAAAAMAwGCiqGJAIBAQEBAgGgggHaMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAcBgkqhkiG9w0BCQUxDxcNMTcwNTE3MTQxNDU3WjAvBgkqhkiG9w0BCQQxIgQgKp3J5UaiRW5erAlFj04TSzEzqW4OxCzPsIRiX0Udh9kwggFrBgsqhkiG9w0BCRACLzGCAVowggFWMIIBUjCCAU4wDAYKKoYkAgEBAQECAQQglxEgC4hcQDrqQ8Chu0VXMcgdi06ummj6vtKcoz+h1gEwggEaMIIBAKSB/TCB+jE/MD0GA1UECgw20JzRltC90ZbRgdGC0LXRgNGB0YLQstC+INGO0YHRgtC40YbRltGXINCj0LrRgNCw0ZfQvdC4MTEwLwYDVQQLDCjQkNC00LzRltC90ZbRgdGC0YDQsNGC0L7RgCDQhtCi0KEg0KbQl9CeMUkwRwYDVQQDDEDQptC10L3RgtGA0LDQu9GM0L3QuNC5INC30LDRgdCy0ZbQtNGH0YPQstCw0LvRjNC90LjQuSDQvtGA0LPQsNC9MRkwFwYDVQQFDBBVQS0wMDAxNTYyMi0yMDEyMQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LICFDAEdR3vLHiuAgAAAAEAAABOAAAAMA0GCyqGJAIBAQEBAwEBBEBvBcp4mxKAg10dNF2efBzQxtq37RcgJtkA0PUgpC4BTlMfQiKe6rSNVcxjj4ZbQUmkPI0Bbp95uFWty+zbtoNvMA0GCyqGJAIBAQEBAwEBBECqXUtlnewapr4CG5+cKu35iQ1k5lbEmfKi0WXAWlfyIIHtzAtHEh21dNjwerYUhQwTci20xaeFV03kGz46Edwy",
"signed_content_encoding":"base64"
}
`

Respnse example:
`{
  "meta": {
    "url": "http://api-svc.il/api/legal_entities",
    "type": "object",
    "request_id": "jabcjib70udb8oak2vd3r8a7hak5herd",
    "code": 404
  },
  "error": {
    "type": "not_found"
  }
}`

**Comment by PavelVesnin** [comment]
PRM pod was updated and fixed this issue

**Comment by lymychp** [comment]
@PavelVesnin  was it deployed to dev?

**Comment by PavelVesnin** [comment]
@lymychp PRM pod was updated - it means, that last version of PRM was deployed to dev
