### ISSUE TITLE
Fix hint for email sender

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/ehealth.api#177]
Replace Andrew Dryga text and picture with correct ehealth info
<img width="795" alt="screen shot 2017-05-22 at 17 05 57" src="https://cloud.githubusercontent.com/assets/12275915/26313793/a6bd67b6-3f14-11e7-87fd-9708022634dc.png">

**Comment by AndrewDryga** [comment]
This happens because I am using Google Apps for our development domain, and it resolves email owner. Production emails MUST be sent from a different domain with other mail service configured by NHS or third-parties, since it's not in project deliverables.
