### ISSUE TITLE
 Import in the region-district-settlement data to the uaddresses db

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#179]
[Addresses repo](https://github.com/Nebo15/uaddresses.api) with the import scripts
Use the file from the #31 as a source of data.

**Comment by lymychp** [comment]
[DB damp with the addresses data](https://drive.google.com/open?id=0BxEHO5wvLxc6aTJNSWJ1X2Q3WGc)

**Comment by AndrewDryga** [comment]
Done.
