### ISSUE TITLE
Auth 2.0 Flow - Verify requested scopes

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/ehealth.api#195]
As a User, I can approve only my available scopes according to my roles in this client
As a User, I can't approve unavailable scopes

Tasks:
- [ ] Verify that requested scopes matches with global scope list
- [ ] Check that user is an active employee at this Legal entity (client)
- [ ] Verify that requested scopes matches with available user scopes

**Comment by lymychp** [comment]
duplicates [72](https://github.com/Nebo15/mithril.api/issues/72)
