### ISSUE TITLE
Approve notifications

### ISSUE THREAD

**Issue by warehousman** [Nebo15/ehealth.api#233]

**Comment by warehousman** [comment]
1) Invitation template
2) Successful registration template

**Comment by kmakarenko** [comment]
Please attach the text/screenshots to be approved (or provide a link)

**Comment by kmakarenko** [comment]
1. Всюду в системі замінити назву E-Health на eHealth

2. Текст e-mail
"Вітаємо!

Вас запрошують приєднатись до системи eHealth, в рамках впровадження в Україні електронної системи охорони здоров’я.

Заклад "**" (*офіційна назва закладу вписана у реєстраційну форму*), що знаходиться за адресою: 
вул. Ніжинська 15, Київ, 02090 (*зазначене у реєстраційній формі місце знаходження*)
Запрошує вас до співпраці на посаду: *зазначена кадровиком назва посади*!

Щоб прийняти запрошення від цього закладу, будь ласка, перейдіть за посиланням: http://auth.dev.ehealth.world/invite?invite=7d34db24-258b-4ea3-8bf0-31fc8e3d317a

Хочу дізнатись більше про умови роботи та співпраці в системі eHealth <link>”

 
3. Текст для показу на сторінках: буде додано протягом дня
2. Створити пароль: Додати друге поле і верификацию, що в обивда поля були введені однакові паролі

**Comment by alexeybondarenko** [comment]
Продублирую, чтобы можно было отмечать выполненные пункты

- [ ] Всюду в системі замінити назву E-Health на eHealth
- [ ] Текст e-mail
- [ ] Створити пароль: Додати друге поле і верификацию, що в обивда поля були введені однакові паролі

**Comment by IrynaShevch** [comment]
Залишити сторінку "реєстрація", прибрати сторінку "прийняти запрошення". 

На сторінці "реєстація" треба внести змінити згідно з текстом нижче: 

Я, ПІБ, 00/00/0000 р.н.
даю згоду на реєстрацію мене в системі eHealth у ролі «лікар».
 
Детальніше
_(до речі, чи є зараз в даних серія паспорту? Бо зараз там тільки номер)_
 
Зверніть увагу, що приймаючи запрошення, Ви погоджуєтесь з положеннями Регламенту функціонування системи eHealth та надаєте згоду адміністратору системи на обробку Ваших персональних даних з метою забезпечення роботи в системі eHealth (електронній системі охорони здоров'я).
 
(місце для галочки) Даю згоду на обробку моїх персональних даних
(місце для галочки) Погоджуюсь з Регламентом функціонування системи eHealth


Після нього сторінка "вітаємо запрошення прийнято"


На сторінці "Положення про конфіденційність та щодо захисту персональних даних та конфіденційної інформації" треба вносити текст регламенту, який ще узгоджується з МІС. 
Надішлю завтра протягом дня.


Якщо щось не можна зробити у цей реліз, а чомусь суперечить - будь ласка, пишіть

**Comment by mmiliaieva** [comment]
Серія паспорту також є, приклад листа вкладено
![image](https://cloud.githubusercontent.com/assets/19431677/26616174/528f22c0-45d5-11e7-946d-cf621716ebbf.png)

**Comment by mmiliaieva** [comment]
Процес погодження запиту на реєстрацію  співробітника зараз складається з двох кроків:
1. Реєстрація в авторизаційній системі або авторизація вже існуючим користувачем
2. Погодження запиту на реєстрацію співробітника, в результаті якого створюється співробітник в prm (сторінка "Прийняти запрошення")
Ці кроки повинні мати саме таку послідовність. Тому об'єднати ці два кроки неможливо на одній сторінці.
Додаю посилання на процес [погодження запрошення](https://edenlab.atlassian.net/wiki/pages/viewpage.action?pageId=1227183)

**Comment by warehousman** [comment]
@all -  "прибрати сторінку "прийняти запрошення"." - сейчас делать не будем, галочки:  (місце для галочки) Даю згоду на обробку моїх персональних даних
(місце для галочки) Погоджуюсь з Регламентом функціонування системи eHealth - разместим на этой странице

**Comment by IrynaShevch** [comment]
👍 Just a reminder: перед этими двумя галочкам нужно еще текст добавить
Зверніть увагу, що приймаючи запрошення, Ви погоджуєтесь з положеннями Регламенту функціонування системи eHealth та надаєте згоду адміністратору системи на обробку Ваших персональних даних з метою забезпечення роботи в системі eHealth (електронній системі охорони здоров'я).

Сверху, после имени и даты рождения пишем текст только про роль:
даю згоду на реєстрацію мене в системі eHealth у ролі «лікар»

**Comment by warehousman** [comment]
На первой странице галочка с согласием на обработку, на второй галочка согласия с регламентом

**Comment by IrynaShevch** [comment]
Я, ПІБ, 00/00/0000
даю згоду на реєстрацію мене в системі eHealth у ролі "лікар".

Детальінше

(Поле для пароля 1)
(Поле для пароля 2)

Зверніть увагу, що приймаючи запрошення, Ви погоджуєтесь на обробку Ваших персональних даних з метою забезпечення роботи в системі eHealth (електронній системі охорони здоров'я).

(Галочка) Даю згоду на обробку моїх персональних даних

(кнопка)

__________

Прийняття Регламенту 

Приймаючи запрошення на роботу в системі eHealth ви також погоджуєтесь з положеннями Регламенту функціонування системи (посилання на регламент - текст поки що не затвердили, можемо покищо кинути білий скрін)

(Галочка) Погоджуюсь з Регламентом функціонування системи eHealth

(Кнопка)

__________
Наступний скрін вас зареєстровано 

=======================
Про посилання на регламент - бажано, але optional

**Comment by alexeybondarenko** [comment]
Готово

![screencapture-auth-dev-ehealth-world-invite-1496249393045](https://cloud.githubusercontent.com/assets/3592553/26643674/c55d91b4-463a-11e7-8bbf-90b4970e1513.png)

![screencapture-auth-dev-ehealth-world-invite-accept-1496249546958](https://cloud.githubusercontent.com/assets/3592553/26643665/bcff5ed0-463a-11e7-9526-e81cc71d336c.png)

![screencapture-auth-dev-ehealth-world-invite-success-1496249556355](https://cloud.githubusercontent.com/assets/3592553/26643661/b9e36dcc-463a-11e7-90d7-b0edc82857d7.png)

**Comment by IrynaShevch** [comment]
@warehousman 
Вместо "галочки": Підтверджую достовірність вказаних мною даних та добровільність надання цих даних. Усвідомлюю, що у випадку надання мною невірної інформації, мені може бути відмовлено у реєстрації в системі eHealth. 

![_1](https://cloud.githubusercontent.com/assets/29067222/26815552/ac0a6a52-4a95-11e7-8e5c-6a515ca57303.png)
![_2](https://cloud.githubusercontent.com/assets/29067222/26815553/ac3c45e0-4a95-11e7-88bc-526ef9f9e37c.png)

**Comment by IrynaShevch** [comment]
@warehousman 
текст "галочки" на МІСі затвердили з юристами: 
Зобов'язуюсь дотримуватись Регламенту функціонування системи eHealth. Підтверджую достовірність вказаних мною даних та добровільність надання цих даних. Усвідомлюю, що у випадку надання мною невірної інформації, мені може бути відмовлено у реєстрації в системі eHealth.

**Comment by alexeybondarenko** [comment]
@IrynaShevch в скриншотах указана ссылка на Регламент функционирования системы. Мы можем этот регламент сейчас разместить на сайте?

**Comment by alexeybondarenko** [comment]
@IrynaShevch не совсем понятно про чекбоксы (галочки). На скриншотах выше они выделены красным цветом. Нужно как то поменять текстовку или нет?

**Comment by IrynaShevch** [comment]
Чекбоксы просто сместились по отношению к тексту. Выровняла, обвела красным, что выравнивала.

Ссылку на регламент смогу скинуть в этот Чт, сейчас он еще утверждается с мисами.

**Comment by alexeybondarenko** [comment]
Спасибо, делаем.

**Comment by alexeybondarenko** [comment]
Done:
https://github.com/Nebo15/nhs.auth.web/pull/25
https://github.com/Nebo15/nhs.auth.web/pull/26

**Comment by IrynaShevch** [comment]
Леша))
В письмах на демо немножечко поменяли текст - Петя внес изменения. Как сказал Петя, его надо будет поменять на проде. 
На всякий случай текст:
"Вітаємо!
Вас запрошують приєднатись до системи eHealth в рамках запровадження в Україні електронної системи охорони здоров’я. 
Заклад "Odesa", що знаходиться за адресою: Ніжинська 15, СОРОКИ-ЛЬВІВСЬКІ, 02090 
Запрошує вас до співпраці на посаду: Головний лікар!
Щоб прийняти запрошення від цього закладу, будь ласка, перейдіть за посиланням: http://auth.demo.ehealth.world/invite?invite=7222d237-289f-43fe-a2fe-82543291007e
Хочу дізнатись більше про умови роботи та співпраці в системі eHealth.
© 2017 Електронна система охорони здоров'я eHealth. Всі права захищено"

"Вітаємо!
Вас було успішно зареєстровано в системі eHealth.
Хочу дізнатись більше про умови роботи та співпраці в системі eHealth.
© 2017 Електронна система охорони здоров'я eHealth. Всі права захищено"

Также, учитывая, что нет НСЗУ (законы не приняли) и мы сейчас работаем чисто от проектного офиса eHealth, нужно будет поменять в письмах и скринах логотип НСЗУ на лого eHealth: https://drive.google.com/open?id=0B9rXAkrOg1wQd3AxUFFOc2FOVDA
Если что, это лого есть у Дианы. 

На одном скрине нужно вставить ссылку на Регламент на фразу "Регламенту функціонування системи": https://ti-ukraine.org/news/rehlament-funktsionuvannia-pilotnoho-proektu-elektronnoi-systemy-okhorony-zdorov-ia/ (скрин прикрепляю, чтобы было понятнее)
![ehealth](https://user-images.githubusercontent.com/29067222/27191913-ff486bce-5201-11e7-95ce-89fb385fbb80.jpg)

**Comment by alexeybondarenko** [comment]
### Портал авторизации

- [ ] поменять логотип на auth
- [ ] проставить ссылку на регламент (https://ti-ukraine.org/news/rehlament-funktsionuvannia-pilotnoho-proektu-elektronnoi-systemy-okhorony-zdorov-ia/)
- [ ] **НСЗ** заменить на **Електронная система охорони здоров'я eHealth**

#### Шаблоны писем

- [ ] поменять логотип в шаблонах писем
- [ ] проставить ссылку на регламент (https://ti-ukraine.org/news/rehlament-funktsionuvannia-pilotnoho-proektu-elektronnoi-systemy-okhorony-zdorov-ia/)
- [ ] Убрать адрес клиники
- [ ] Добавить кавычки вокруг должности

**Comment by lymychp** [comment]
нова текстовка листа-запрошення від @IrynaShevch 

---
Вітаємо!
Заклад “_______“, що знаходиться за адресою: ______, зареєстровано в системі eHealth в рамках впровадження в Україні електронної системи охорони здоров‘я.

Вас запрошено пройти реєстрацію в системі eHealth як співробітник цього закладу.
Ваша посада: __________________

Щоб прийняти запрошення, будь ласка, перейдіть за посиланням: ______

Хочу дізнатись більше про умови роботи та співпраці в системі eHealth.

**Comment by alexeybondarenko** [comment]
done
