### ISSUE TITLE
Approve dictionaries

### ISSUE THREAD

**Issue by warehousman** [Nebo15/ehealth.api#235]

**Comment by warehousman** [comment]
Approve dictionaries with Katya

**Comment by warehousman** [comment]
https://docs.google.com/spreadsheets/d/1Cu7YFECaTjKkrcvorusVHIyM8MpB2WsXGO4nHlKuGBw/edit?usp=sharing

**Comment by kmakarenko** [comment]
[dictionary.xlsx](https://github.com/Nebo15/ehealth.api/files/1033107/dictionary.xlsx)
In attachment with comments from Iryna

**Comment by warehousman** [comment]
Guys! please update dictionaries according to feedback provided.
Ira please follow-up this issue

**Comment by AlekzandrV** [comment]
https://docs.google.com/spreadsheets/d/1Cu7YFECaTjKkrcvorusVHIyM8MpB2WsXGO4nHlKuGBw/edit#gid=0
Updated descriptions except settlement type

**Comment by warehousman** [comment]
@kmakarenko Please approve updated version

**Comment by IrynaShevch** [comment]
as discussed, i've reduced the number of legal entity types - crossed out extra ones. but legals say that the list should be wider in the future;
added some street types;
all changes are marked in yellow.

https://docs.google.com/spreadsheets/d/1Cu7YFECaTjKkrcvorusVHIyM8MpB2WsXGO4nHlKuGBw/edit?ts=592d6c02#gid=0

**Comment by AlekzandrV** [comment]
Updated on Dev/Demo
