### ISSUE TITLE
404 Error Legal_entity PUT

### ISSUE THREAD

**Issue by mmiliaieva** [Nebo15/ehealth.api#241]
1. Service Legal_entity PUT responed with 404 Error
2. There is no email with link

Response example:
`{
  "meta": {
    "url": "http://api-svc.il/api/legal_entities",
    "type": "object",
    "request_id": "iu0n5lpcrh70u1dlfsecok0rauf752e3",
    "code": 404
  },
  "error": {
    "type": "not_found"
  }
}`

**Comment by AlekzandrV** [comment]
#240
