### ISSUE TITLE
create PRM, Addresses, MPI, OPS_DB replica

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#245]
pipelene streaming should be used. 
All the personalized data should be excluded:
- ukr_med_registeries, global_parameters delete from replica
- parties table must contain only id
erd diagram - https://github.com/Nebo15/ehealth.api/blob/master/specs/database_schema/reporting.erd

- [x] prepare the specs of views
- [x] create views with the aggregated data
- [x] failover

**Comment by vsirius** [comment]
Done
