### ISSUE TITLE
Remove unique constraint from client.name on Mithril

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/ehealth.api#253]
As a MIS user
I should be able to register more than one legal entity with the same name

- [x] Remove unique constraint on client.name at Mithril

Acceptance criteria:
- [ ] No errors on Register new Legal entity with repeating Legal Entity name
- [ ] More than one Client in Mithril with the same name

#240

**Comment by gmile** [comment]
This was done in https://github.com/Nebo15/mithril.api/commit/5e0128aa77649fa99c7965c3d5d7cbfc95e4e2eb
