### ISSUE TITLE
Import streets-houses from the red-lists

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#273]
Use the below [source](https://drive.google.com/drive/folders/0BxLkmYnn2AJ7NE1XNlRQek9QT1E)

**Comment by lymychp** [comment]
is blocked by #291

**Comment by lymychp** [comment]
red-lists are delayed. In order to complete development we agreed to load some data from the UkrPost file just for the testing purposes.

**Comment by AlekzandrV** [comment]
Test data imported
