### ISSUE TITLE
Password management

### ISSUE THREAD

**Issue by warehousman** [Nebo15/ehealth.api#278]
As user i want to be able to reset/set new  password

**Comment by lymychp** [comment]
- [ ] FE
- [ ] BE mithril

**Comment by AndrewDryga** [comment]
TODOs:
- [X] API docs
- [ ] Man template design
- [ ] Man template layout
- [ ] Additional GW routes
- [X] Mithril code changes & tests
- [ ] IL code changes & tests
- [ ] Deployment

**Comment by AndrewDryga** [comment]
Deployment task: https://github.com/Nebo15/ehealth.api/issues/278

**Comment by AndrewDryga** [comment]
@AlekzandrV close this task after test please, but I did everything to make sure it works on dev (`curl` samples are in Slack).

**Comment by AlekzandrV** [comment]
Previously created tokens remains valid after password was changed:
- [ ] Deactivate tokens when password changed

Password changed (response):
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/credentials_recovery_requests/1391a215-520f-4c83-b520-0b9f2b892b93/actions/reset_password",
        "type": "object",
        "request_id": "o8qffaao0jqo7mj2vm3hlo8himm25uav",
        "code": 200
    },
    "data": {
        "settings": {},
        "id": "fee23115-2e61-4b48-abad-f00cee8fecf3",
        "email": "sp.virny+101@gmail.com"
    }
}
```

Request Legal entities with "invalid" token:
```
curl -X GET \
  http://dev.ehealth.world/api/legal_entities \
  -H 'authorization: Bearer SGFFcERQYlR1YnoxVzRGbTFmelE0dz09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 7f4bb4d2-a134-87ab-e325-164307f6ccb9'
```

Expected result:
401

Actual result:
200

**Comment by AndrewDryga** [comment]
We had a call with Alex and agreed that right now everything works as expected.
