### ISSUE TITLE
Provide the Ukr. Med registry data

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#29]

**Comment by warehousman** [comment]
https://drive.google.com/drive/folders/0B9rXAkrOg1wQZTFHTFAwTFctSHM

**Comment by lymychp** [comment]
The provided data should be verified.
Please check the lists and clean it up.
There should be no duplicates on the `edrpou` field.

**Comment by lymychp** [comment]
data has been provided
