### ISSUE TITLE
Employee.Position validation against dictionary

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#297]
Postion should be dictionary, not string

- [x] Create Legal_Entity Owner.Position add dictionary validation
- [x] Create Employee_Request Employee.Position  add dictionary validation
- [x] Create Employee_Request. Use dictionary value not id in the email notification template.
- [x] update json schema definition https://github.com/Nebo15/ehealth.api/commit/db651e19e30d2d421d58848dca1891e43c9700b6 https://github.com/Nebo15/ehealth.api/commit/1cfcd0a6dff99cc8d9228b331b6352385fa2d29c
- [x] auth FE - Use  Position dictionary value not id in the email notification template.
- [x] update apiary spec for legal entity and employee request https://github.com/Nebo15/ehealth.api/commit/4ccab3bb787a71774696fca8c6d73e10e09708dc

**Comment by lymychp** [comment]
@AlekzandrV implementation done and deployed to demo. But we should update the spec

**Comment by AlekzandrV** [comment]
@lymychp spec and schema updated
