### ISSUE TITLE
Settlement_ID validation

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#298]
As a NHS 
I want the settlement_ID from the payload to be searched in the UAddresses dictionary
So that I will get the clean address data in my DB

- [x] create legal_entity - all the addresses
- [ ] create employee_request - all the addresses
- [ ] Get services with addresses should return Settlement ID, Settlement Name, Region_name, District_Name from the UAddresses

**Comment by lymychp** [comment]
district_name, region_name should be also validated against settlement_id

**Comment by AlekzandrV** [comment]
- [x] create legal_entity - all the addresses
Done
- [ ] ~create employee_request - all the addresses~
Invalid requirement. Employee request does not contain addresses
- [ ] ~Get services with addresses should return Settlement ID, Settlement Name, Region_name, District_Name from the UAddresses~
Requirement revoked

- [x] create legal_entity - all the addresses - Tested
