### ISSUE TITLE
Trial announcement

### ISSUE THREAD

**Issue by warehousman** [Nebo15/ehealth.api#301]
От Хелси пришел запрос: Є декілька питань по листу підтвердження реєстрації.
В тому вигляді в якому він є зараз він більше підходить для всіх співробітників крім "Керівника".
Для куріника пропоную змінити текст на:
"Вітаємо!
Ви зробили перший крок в рамках впровадження в Україні електронної системи охорони здоров'я.
Цим листом ми підтверджуємо, що заклад "...", який зареєстровано за адресою: ..... зареєстровано в системі eHealth.

Для завершення реєстрації, будь ласка, перейдіть за посиланням:

........
"

**Comment by IrynaShevch** [comment]
поговорили с катей, ничего не меняем
