### ISSUE TITLE
Scopes improvements and GW proxy configuration

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/ehealth.api#307]
As a NHS Admin
I want to limit scopes for some users to create new employees via employee requests, sign declaration requests etc.
so we have to improve scopes model and GW configuration

**Existing model:**
`<resourcse|service>:<action>`

Available service(pattern):
`<host>/api/<resource>/*`

Available actions:
- read (e.g., GET)
- write (e.g., PUT, POST, PATCH)

**Proposed model:**
`<resourcse|service + (id?) + (action?)>:<action>`

Available service(pattern):
`<host>/api/<resource>/ ( {:id}/action )?` - resource id and its action is optional

Available actions:
- read (e.g., GET)
- write (e.g., PUT, POST, PATCH)
- approve (e.g., PUT, POST, PATCH)
- reject (e.g., PUT, POST, PATCH)
- sign (e.g., PUT, POST, PATCH)
etc

See proposed [role scopes](https://edenlab.atlassian.net/wiki/display/EH/Scopes+model)

- [x] Add new scopes to `mithril` configuration (done as of [a9c6633](https://github.com/Nebo15/mithril.api/blob/a9c66331bf896db1032c010a4b5507feba082773/config/config.exs#L72-L82)),
- [x] Configure roles on mithril (see https://github.com/Nebo15/ehealth.api/issues/307#issuecomment-306755768 for details):
  - [x] configure on dev environment,
  - [x] configure on demo environment,
  - [x] configure on prod environment,
- [x] Improve GW plugs to support complex API paths,
- [x] Walk through all existing routes in gateway, verifying that route satisfies scope requirements as listed [here](https://edenlab.atlassian.net/wiki/display/EH/Scopes+model) @AlekzandrV,
- [x] Add new scopes to dictionary @AlekzandrV

**Comment by lymychp** [comment]
@gmile please estimate

**Comment by gmile** [comment]
We cannot do this:
```
<resourcse|service + (id?) + (action?)>:<action>
```
Scopes by definition mean "c class of something". We cannot point to ids, e.g. instances of something.

Therefor I suggest the above model remains the same, e.g. `<resourcse|service>:<action>`, with only extension that `action` can be anything, not just `read`/`write` as before.

**Comment by gmile** [comment]
@AlekzandrV here – https://edenlab.atlassian.net/wiki/display/EH/Scopes+model – I can see a "General" category.

In it, it is said that anyone (any user) can access addresses and dictionaries. That said, does "any user" include users not registered in our system? If so – do we even need to have scopes?

Can we just open uaddresses / dictionaries endpoints publicly without specifying scopes?

**Comment by gmile** [comment]
> Improve GW plugs to support complex API paths,

@AlekzandrV can you elaborate on this please?

Right now we already have an ability to define & distinguish routes like this:

```
/posts/:id
/posts/:id/approve
/posts/:id/comments/:comment_id/delete
/posts/:id/comments/:comment_id/some_action
```
etc.

Since we can distinguish the routes above, we can set scopes precisely for each route. 

That said I think we already support complex routes as per your saying, but I'll leave it for you to confirm.

**Comment by gmile** [comment]
> Add new scopes to dictionary

@AlekzandrV can you please elaborate on this one as well? Where exactly dictionary is stored?

**Comment by gmile** [comment]
Double-checked that all envs (dev, demo, prod) have the same scopes for all roles, per [Scopes model](https://edenlab.atlassian.net/wiki/display/EH/Scopes+model)

**Comment by gmile** [comment]
@AlekzandrV in [Scopes model](https://edenlab.atlassian.net/wiki/display/EH/Scopes+model) we distinguish roles and client types. Right now there is a client type MIS who may request `legal_entity:write`, but there's no user (not in the document) who can provide this scope.

Maybe we should add auxiliary MIS user to make the picture more complete?

**Comment by gmile** [comment]
<details>
<summary>Routes on dev</summary>

```
GET     /apis_dashboard
POST    /digital_signatures
GET     /api/employee_requests/_%
POST    /api/employee_requests                  employee_request:write
GET     /api/employee_requests                  employee_request:read
POST    /oauth/tokens
GET     /admin/client_types
POST    /admin/client_types
GET     /admin/clients/_%
GET     /il
POST    /il
GET     /prm
POST    /prm
GET     /api/dictionaries
PATCH   /api/dictionaries
GET     /api/uaddresses                         address:read
POST    /api/employees                          employee:write
PUT     /api/employees                          employee:write
GET     /api/employees                          employee:read
POST    /ABC
GET     /apis_status
GET     /api/test
PUT     /api/test
POST    /templates
GET     /templates
PUT     /templates
DELETE  /templates
POST    /api/employee_requests/_%/user
POST    /users/login                            session:read session:write
GET     /admin/tokens/_%/verify
GET     /admin/users
POST    /oauth/apps/authorize                   app:authorize
GET     /api/legal_entities                     legal_entity:read
PUT     /api/legal_entities                     legal_entity:write
GET     /api/global_parameters
PUT     /api/global_parameters
```

</details>
<details>
<summary>Routes on demo</summary>

```
GET     /apis_dashboard
POST    /digital_signatures
GET     /api/employee_requests/_%
POST    /api/employee_requests                  employee_request:write
GET     /api/employee_requests                  employee_request:read
POST    /oauth/tokens
GET     /admin/client_types
POST    /admin/client_types
GET     /admin/clients/_%
GET     /il
POST    /il
GET     /prm
POST    /prm
GET     /api/dictionaries
PATCH   /api/dictionaries
GET     /api/uaddresses                         address:read
POST    /api/employees                          employee:write
PUT     /api/employees                          employee:write
GET     /api/employees                          employee:read
POST    /ABC
GET     /apis_status
GET     /api/test
PUT     /api/test
POST    /templates
GET     /templates
PUT     /templates
DELETE  /templates
POST    /api/employee_requests/_%/user
POST    /users/login                            session:read session:write
GET     /admin/tokens/_%/verify
GET     /admin/users
POST    /oauth/apps/authorize                   app:authorize
GET     /api/legal_entities                     legal_entity:read
PUT     /api/legal_entities                     legal_entity:write
GET     /api/global_parameters
PUT     /api/global_parameters
```
</details>
<details>
<summary>Routes on prod</summary>
GET     /apis_dashboard
POST    /digital_signatures
GET     /api/employee_requests/_%
POST    /api/employee_requests                  employee_request:write
GET     /api/employee_requests                  employee_request:read
POST    /oauth/tokens
GET     /admin/client_types
POST    /admin/client_types
GET     /admin/clients/_%
GET     /il
POST    /il
GET     /prm
POST    /prm
GET     /api/dictionaries
PATCH   /api/dictionaries
GET     /api/uaddresses                         address:read
POST    /api/employees                          employee:write
PUT     /api/employees                          employee:write
GET     /api/employees                          employee:read
POST    /ABC
GET     /apis_status
GET     /api/test
PUT     /api/test
POST    /templates
GET     /templates
PUT     /templates
DELETE  /templates
POST    /api/employee_requests/_%/user
POST    /users/login                            session:read session:write
GET     /admin/tokens/_%/verify
GET     /admin/users
POST    /oauth/apps/authorize                   app:authorize
GET     /api/legal_entities                     legal_entity:read
PUT     /api/legal_entities                     legal_entity:write
GET     /api/global_parameters
PUT     /api/global_parameters
</details>

**Comment by lymychp** [comment]
@AlekzandrV  please close or feedback if needed
