### ISSUE TITLE
Change address in the invitation line

### ISSUE THREAD

**Issue by kmakarenko** [Nebo15/ehealth.api#313]
Action:
During legal entity registration enter the following address:
{ "zip" : "61000", "type" : "RESIDENCE", "street_type" : "SQUARE", "street" : "С. Бандери", "settlement_id" : "19d2fca8-98bd-494a-a47c-9ef64c5163fd", "region" : "Богодухівський", "country" : "UA", "building" : "11", "area" : "Харківська", "apartment" : "1" }

Current result:
The following address is displayed in invitation e-mail:
Заклад "Назва 1", що знаходиться за адресою: С. Бандери 11, , 61000 

Expected result:
The following address is displayed in invitation e-mail:
Заклад "Назва 1", що знаходиться за адресою: Харківська область, Богодухівський район, місто Богодухів, площа С. Бандери 11, квартира 1, 61000

**Comment by mmiliaieva** [comment]
Tests passed
