### ISSUE TITLE
Register Helsi on production env

### ISSUE THREAD

**Issue by warehousman** [Nebo15/ehealth.api#325]
Data to be provided by Kostiantyn:
- [ ] MIS email
- [ ] MIS public name

**Comment by gmile** [comment]
@warehousman btw we already registered Helsi, but with temp email/nam. As soon as actual email * name are provided, I will update existing ones

**Comment by warehousman** [comment]
OK, please provide Helsi MIS secret using secured channel so i can provide it to them

**Comment by gmile** [comment]
Passed the secret in private to @warehousman
