### ISSUE TITLE
[Public API] Get Employees List

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#333]
- [x] Implement the subj. service according to the [spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/employees/get-employees-list)
[Basic logic](https://edenlab.atlassian.net/wiki/display/EH/IL.Get+Employees+List)
- [ ] auth, scopes check on GW @gmile

**Comment by gmile** [comment]
@lymychp this is assigned to current, sprint, right?

**Comment by lymychp** [comment]
@gmile yep

**Comment by gmile** [comment]
@AlekzandrV from reading [IL.Get Employees List](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/employees/get-employees-list):

> Check user scopes in order to perform this action

What exact scopes do we need here?

**Comment by AlekzandrV** [comment]
@gmile Employee:read

**Comment by mmiliaieva** [comment]
Missing object doctor in response, if "employee_type": "DOCTOR"

**Comment by mmiliaieva** [comment]
In Response internal_error 500

Request Example:
`curl -X GET \
  http://dev.ehealth.world/api/employees \
  -H 'authorization: Bearer WHhlUmpJN0xJcGJnSEwwTkNkQ2ZTQT09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 7e264447-ad61-c1cb-d82b-38d9f9fe527e'`

Response Exapample:
`{
  "meta": {
    "url": "http://dev.ehealth.world/api/employees",
    "type": "object",
    "request_id": "elggtsgv076agcf3ik0cilt0kms5h9on",
    "code": 500
  },
  "error": {
    "type": "internal_error"
  }
}`

**Comment by mmiliaieva** [comment]
1. Service should respond only with active employees (is_active = true)
2. Don't work filter in service parameters
`curl -X GET \
  'http://dev.ehealth.world/api/employees?limit=2&type=DOCTOR' \
  -H 'authorization: Bearer eVFnWHhzZ0tqODdDQ0ZMNXZkQTUyUT09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 3f90beba-2dc3-a4e0-b4c4-3b83f08c0354'`
3. Delete from response:
$.data.inserted_by
$.data.updated_by
$.data.is_active
$.data.doctor.science_degree
$.data.doctor.qualifications
$.data.doctor.educations
4. Missing parameters in response
$.data.doctor.id

**Comment by PavelVesnin** [comment]
@mmiliaieva use `employee_type` instead of `type`

**Comment by mmiliaieva** [comment]
Approved, postman tests passed
