### ISSUE TITLE
New Declaration form changes

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#378]
В рамках анализа последней версии печатной формы декларации, требуется внести следующие изменения:
1. Сервис: Create declaration request
*a)* Согласно пункту 7, 24, 36 печатной формы, необходимо выводить два поля, на данный момент сохраняем одним. 
Объект:  `Person`
Удалено:
birth_place (string, required)
Добавлено:
birth_country (string, required)
birth_settlement (string, required)
*b)* Согласно пункту 14, необходимо добавить новый атрибут в систему.
Объект:  `Person`
Добавлено:
service_location_consent (boolean, required)
*c)* Согласно пункту 28, необходимо разделять типы документов на “посвiдчуе особу” и “пiдтверджуе факт представництва”
Объект: `Document`
Добавлено:
identifies: PERSON (enum, required)
    - PERSON
    - RELATIONSHIP
*d)* Согласно пунктам 1-Б и 1-В, необходимо изменить объект на массив, так как предпологается множественное количество записей. Также необходимо добавить понимание “главного” представителя и “второстепенных”
Объект: `Confidant_Person`
Объект заменен на массив.
Удалено:
birth_place (string, required)
Добавлено:
birth_country (string, required)
birth_settlement (string, required)
relation_type: PRIMARY (enum, required)
    - PRIMARY
    - SECONDARY
2. При обсуждение с @katymak деталей печатной формы, было принято решение внести некоторые изменения в валидацию запроса.
JSON Schema: new_legal_entity_schema
*a)* Убрать обязательность объекта `accreditation`
*b)* Установить обязательность массива `licenses`
*c)* Установить проверку на массив `confidant_person`: если массив передан, должен быть один, но не более, объект с аттрибутом `relation_type: PRIMARY`

**Comment by lymychp** [comment]
@kmakarenko please approve

**Comment by kmakarenko** [comment]
approved

**Comment by gmile** [comment]
@DPashchenko we have these changes included in our latest schema, right?
