### ISSUE TITLE
update kved validation logic

### ISSUE THREAD

**Issue by pzhuk** [Nebo15/ehealth.api#393]
reference support ticket https://github.com/ehealth-ua/api-spec/issues/26

KVed validation process should be updated. 
During validation of the kved list , there should be AT LEAST ONE of allowed kveds (86.10, 86.21, 86.22, 86.90), instead of ONLY ALLOWED kveds from the list as it's done now

**Comment by pzhuk** [comment]
cc @warehousman

**Comment by lymychp** [comment]
the problem described in  https://github.com/ehealth-ua/api-spec/issues/26
is related to the implementation of the requirement - `kved cannot be updated.`
We will update the implementation to make it more obvious #379 
Current implementation already includes the mentioned KVEDS:
```json
 "kveds": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "86.10",
          "86.21",
          "86.22",
          "86.90"
        ]
      },
```
propose to close this ticket
