### ISSUE TITLE
Filters for Users

### ISSUE THREAD

**Issue by alexeybondarenko** [Nebo15/ehealth.api#404]

**Comment by alexeybondarenko** [comment]
- [ ] email

**Comment by alexeybondarenko** [comment]
@warehousman, @AndrewDryga  for this case we need search in users by part of an email. Could we add this to Mithril API?

**Comment by AndrewDryga** [comment]
@alexeybondarenko Can you give more detailed use-case why do you need this?

**Comment by alexeybondarenko** [comment]
@AndrewDryga we need to add search to the list of the users in a mithril admin. Email is only one filter, that is currently available in API. So we want to add a search by a part of an email to simplify a search process for administrators.
