### ISSUE TITLE
Filters for tokens

### ISSUE THREAD

**Issue by alexeybondarenko** [Nebo15/ehealth.api#408]
- [x] user
- [x] names
- [x] value

**Comment by alexeybondarenko** [comment]
name - refresh_token, access_token

**Comment by ivchenkodima** [comment]
@alexeybondarenko api is not filtering the data using params

**Comment by ivchenkodima** [comment]
- [ ] add this issue in API. Now its not realized.

**Comment by alexeybondarenko** [comment]
https://github.com/Nebo15/ehealth.api/issues/505
