### ISSUE TITLE
Update mountain_group on settlement uaddresses

### ISSUE THREAD

**Issue by mmiliaieva** [Nebo15/ehealth.api#412]
Update mountain_group using file

**Comment by mmiliaieva** [comment]
[населені пункти гірської групи.zip](https://github.com/Nebo15/ehealth.api/files/1094897/default.zip)

**Comment by mmiliaieva** [comment]
[населені пункти гірської групи1.zip](https://github.com/Nebo15/ehealth.api/files/1094927/1.zip)

**Comment by AlekzandrV** [comment]
Duplicate records in csv:
```
ЛЬВІВСЬКА ОБЛАСТЬ,Старосамбірський район,с, Поляна
ЛЬВІВСЬКА ОБЛАСТЬ,Старосамбірський район,с, Поляна
```

Duplicate records as matching result:
```
ЛЬВІВСЬКА,	СТАРОСАМБІРСЬКИЙ,	ПОЛЯНА
ЛЬВІВСЬКА,	ДРОГОБИЦЬКИЙ,	ДОВГЕ
ІВАНО-ФРАНКІВСЬКА,	<null>,	ПОЛЯНИЦЯ
```

**Comment by mmiliaieva** [comment]
![image](https://user-images.githubusercontent.com/19431677/27470552-348507f6-57fd-11e7-9bce-fe144a415e5b.png)

**Comment by mmiliaieva** [comment]
[населені пункти гірської групи2.zip](https://github.com/Nebo15/ehealth.api/files/1097485/2.zip)
