### ISSUE TITLE
Dashboards. Main Stats WS

### ISSUE THREAD

**Issue by mmiliaieva** [Nebo15/ehealth.api#434]
As a Portal users I want to see declarations, doctors, msps stats with filters: on date, period
WS [specs](http://docs.ehealthapi1.apiary.io/#reference/internal.-portal-and-reports/mainstats/get-main-stats)

**Comment by TarasenkoA** [comment]
pass
"Dashboards - Get main stats" - test in "901.Dashboars" folder
