### ISSUE TITLE
Owner deactivation workaround

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#453]
As a HNS Admin
I want to have only one active legal entity owner
so that there will be no duplicates

Approve Employee [Updated specs](https://edenlab.atlassian.net/wiki/pages/viewpage.action?pageId=1316436) 
Changes:
Create new employee:
  If employee_type = 'OWNER': deactivate all other records with the employee_type = 'OWNER' for the   legal_entity, where new owner is creating:

```sql
update employees e 
set is_active = false
inserted_by = $new_owner_id
inserted_at = md5(clock_timestamp()
where e.legal_entity_id = $employee_request.legal_entity_id
and e.employee_type = 'OWNER'
```
**Acceptance criteria:**
- [x] create new employee with the employee_type = owner - old owners has been deactivated
- [x] call create legal_entity with the same edrpou as existing one - old owners has been deactivated

**Comment by mmiliaieva** [comment]
Tests passed
