### ISSUE TITLE
Client type in x-consumer-metadat

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/ehealth.api#457]
Add client_type_id and client_type_name from mithril.client to x-consumer-metadata

Attributes:

- client_type_id - mithril.client_client_types.client_type_id
- client_type_name - mithril.client_types.name

Proposed structure:
```
{
  "scope": "employee_request:write employee_request:read legal_entity:read division:read division:write employee:read",
  "refresh_token": "OCtHQVl3NEdqSHFEVi9RV1FCV2VVUT09",
  "redirect_uri": "http://example2.com",
  "grant_type": "authorization_code",
  "client_id": "9c81824b-bc13-4d07-bc76-b069e2a2876b",
  "client_type_id": "a6d2f650-ee0f-4114-a250-eee15ee8c52d",
  "client_type_name": "MIS"
}
```

**Comment by gmile** [comment]
This was done differently as discussed on slack. The change was on mithril: https://github.com/Nebo15/mithril.api/pull/71

**Comment by gmile** [comment]
@AlekzandrV deploying right now...
