### ISSUE TITLE
Import missing settlements

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/ehealth.api#467]
Import missing settlements to Preprod and Prod:

```
psql <DB> --username=<USERNAME> --password -f settlements_fix_19062017.sql
```
[settlements_fix_19062017.sql.zip](https://github.com/Nebo15/ehealth.api/files/1085250/settlements_fix_19062017.sql.zip)

**Comment by AndrewDryga** [comment]
Done for prod and preprod.

**Comment by lymychp** [comment]
restart service is required in order to reload the cache.
Should be done on both: preprod and prod.

**Comment by AndrewDryga** [comment]
@lymychp already done.
