### ISSUE TITLE
add optional login attribute to "Show login UI"

### ISSUE THREAD

**Issue by pzhuk** [Nebo15/ehealth.api#482]
In order to simplify login procedure, we would like to add optional attribute to "Show login UI"
http://docs.ehealthapi1.apiary.io/#reference/internal.-authorization-provider/login-ui/show-login-ui

There should be an optional argument of login, so any MIS initiating login flow could pass this argument 

cc: @warehousman

**Comment by pzhuk** [comment]
guys, any chance you could prioritize it? appreciate it

**Comment by lymychp** [comment]
already deployed to demo
