### ISSUE TITLE
Creating / updating objects

### ISSUE THREAD

**Issue by gmile** [Nebo15/ehealth.api#5]
I has come to my attention that right now it is assumed that during object creation / update process we send a POST / PATCH body [**that is fully occupied by the object in question**](https://github.com/Nebo15/ehealth.api/blob/master/apiary.apib#L272-L273).

I suggest we **do not occupy the root-level object fully**, keeping it available for other attributes. It will make a room for additional attributes in future, in case the need arises.

In short, right now we send the following body in PATCH/POST requests. I suggest we change it from:

```json
{
  "id":1,
  "some_field": "some_value"
}
```
to:
```json
{
  "doctor": {
    "id":1,
    "some_field": "some_value"
  }
}
```
In future it will allow us to supply additional parameters that must be taken into account during record creation. E.g. do this:
```json
{
  "some_metadata": {
    "some_key":"some_value"
  },
  "doctor": {
    "id":1,
    "some_field": "some_value"
  }
}
```

This is a common practice presented in [jsonapi](http://jsonapi.org/format/#crud-creating) (not 1:1, but in _some_ form).

It is also promoted by [phoenix's json generators](https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phx.gen.json/controller.ex#L14-L21) themselves, which results in this – note the nesting of `msp_params` inside "msp" key:

```elixir
def create(conn, %{"msp" => msp_params}) do
  with {:ok, %MSP{} = msp} <- MSPAPI.create_msp(msp_params) do
    conn
    |> put_status(:created)
    |> put_resp_header("location", msp_path(conn, :show, msp))
    |> render("show.json", msp: msp)
  end
end
```

**Comment by gmile** [comment]
@AndrewDryga @lymychp need your input

**Comment by AndrewDryga** [comment]
I don't have any valid opinions on this part, except 'less is better" :).

We don't really need metadata in prm/mpi services, but may need some in integration layer, but we structure it in a way when data looks like an "entity" with optional/required fields.

**Comment by lymychp** [comment]
@gmile I wouldn't spend time for that right now. Our api and even data model is not stable currently. Let's consider it in the next releases for the map, not demo.

**Comment by AndrewDryga** [comment]
Added this to our API manifest, agree that it can be usable in _some_ cases. But we try to use clean REST endpoints that don't accept any side-metadata.
