### ISSUE TITLE
Update mountain group in UAddresses

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/ehealth.api#506]
Update mountain group in UAddresses:

```
psql <DB> --username=<USERNAME> --password -f mountain_cities.sql
```
[mountain_cities.sql.zip](https://github.com/Nebo15/ehealth.api/files/1101892/mountain_cities.sql.zip)

#412

**Comment by lymychp** [comment]
should be updated on dev and  demo first

**Comment by vsirius** [comment]
done
