### ISSUE TITLE
Add search parameters in Get Legal Entities

### ISSUE THREAD

**Issue by mmiliaieva** [Nebo15/ehealth.api#514]
As NHS admin I want search legal entities by legal_entity_id and settlement_id 
See [specs](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/get-legal-entities)

**Comment by PavelVesnin** [comment]
@mmiliaieva rename `legal_entity_id` to `id`, because it's database field name

**Comment by mmiliaieva** [comment]
List of legal_entities is empty, if the service is called by MIS
`curl -X GET \
  http://dev.ehealth.world/api/legal_entities \
  -H 'authorization: Bearer ak0vVzZmK0k1UmZGUkVBMm4ybFVSdz09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 8ee98b76-05fc-7a5f-59d1-543d4f18a690'`

Response
`{
  "paging": {
    "size": null,
    "limit": 50,
    "has_more": false,
    "cursors": {
      "starting_after": null,
      "ending_before": null
    }
  },
  "meta": {
    "url": "http://dev.ehealth.world/api/legal_entities",
    "type": "list",
    "request_id": "1a9o2mc28gh0d67a4vsvp3mlju48l70u",
    "code": 200
  },
  "data": []
}`

Expected result: List of all legal entities

**Comment by TarasenkoA** [comment]
Service work incorrectly in case with fail id (in response send info)

GET /api/legal_entities?id!=9c81824b-bc13-4d07-bc76-b069e2a2876b HTTP/1.1
Host: dev.ehealth.world
Authorization: Bearer OUZtWk9ITHp4TENia2QxM25nTkhBdz09
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 598907f2-cfe8-0052-1d5a-c8042cab4a50

**Comment by PavelVesnin** [comment]
@TarasenkoA `Service work incorrectly` sounds ambiguous. Write please expected result and actual.
`id!=` - as I understand, you expected search legal_entities that doesn't match passed id. This is not supported by http protocol. Valid query params is `key=value` pairs. See [rfc](https://tools.ietf.org/html/rfc3986#section-3.4)
So in this request you can filter only by params that match with legal_entity attributes.

**Comment by TarasenkoA** [comment]
Try to send case - `Get Legal Entities for another legal_entity` and have `"code": 404` with token for another MSP.  

request
GET /api/legal_entities HTTP/1.1
Host: dev.ehealth.world
Authorization: Bearer VjFmL3F0QWhzNmVLYXNCUXJRZzg4QT09
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 3852cbce-11a6-ef21-5dd5-7e28424d0853

response
{
  "meta": {
    "url": "http://dev.ehealth.world/api/legal_entities",
    "type": "object",
    "request_id": "mgkhi4rhaoeknhhjv7ks29ib65rcr7p0",
    "code": 404
  },
  "error": {
    "type": "not_found"
  }
}

`Expected Result:` code: 200 and no data in response

**Comment by TarasenkoA** [comment]
For token with able to handle in Legal Entity - `RWFHNkF6RTRPOGdvd3V4TlgwWStXQT09` (type = MIS) i have different response in services:
`Get Legal Entity by ID for another legal_entity` - incorrectly

request
```
GET /api/legal_entities/9c81824b-bc13-4d07-bc76-b069e2a2876b HTTP/1.1
Host: dev.ehealth.world
Authorization: Bearer RWFHNkF6RTRPOGdvd3V4TlgwWStXQT09
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 6171dbd9-f82d-7b59-fec6-e2ddf51b51fd
```
response
```
{
  "urgent": {
    "security": {
      "redirect_uri": "http://example2.com",
      "client_secret": "TDA5K2I3UkNWZXIwWkwzcmcyVEQwZz09",
      "client_id": "9c81824b-bc13-4d07-bc76-b069e2a2876b"
    }
  },
  "meta": {
    "url": "http://dev.ehealth.world/api/legal_entities/9c81824b-bc13-4d07-bc76-b069e2a2876b",
    "type": "object",
    "request_id": "9cnong5pc9ciks9qo2i3rdlfkla6m6q3",
    "code": 200
  },
  "data": {
    "updated_by": "ca5a94eb-ff85-46d4-abd7-1ca95a911f40",
    "updated_at": "2017-07-06T13:36:33.298850",
    "type": "MSP",
    "status": "ACTIVE",
    "short_name": "Адоніс22",
    "public_name": "Адоніс22",
    "phones": [
      {
        "type": "MOBILE",
        "number": "+380503410870"
      }
    ],
    "owner_property_type": "STATE",
    "nhs_verified": false,
    "name": "Клініка Адоніс22",
    "mis_verified": "VERIFIED",
    "medical_service_provider": {
      "licenses": [
        {
          "what_licensed": "реалізація наркотичних засобів",
          "license_number": "fd123443",
          "issued_date": "1991-08-19",
          "issued_by": "Кваліфікацйна комісія",
          "expiry_date": "1991-08-19",
          "active_from_date": "1991-08-19"
        }
      ],
      "accreditation": {
        "order_no": "fd123443",
        "order_date": "1991-08-19",
        "issued_date": "1991-08-19",
        "expiry_date": "1991-08-19",
        "category": "FIRST"
      }
    },
    "legal_form": "140",
    "kveds": [
      "86.21"
    ],
    "is_active": true,
    "inserted_by": "ca5a94eb-ff85-46d4-abd7-1ca95a911f40",
    "inserted_at": "2017-06-16T06:41:48.571051",
    "id": "9c81824b-bc13-4d07-bc76-b069e2a2876b",
    "email": "sp.virny+100@gmail.com",
    "edrpou": "38782323",
    "created_by_mis_client_id": "f5e6a307-7c26-404a-8134-b0ea3690152d",
    "addresses": [
      {
        "zip": "02090",
        "type": "REGISTRATION",
        "street_type": "STREET",
        "street": "вул. Ніжинська",
        "settlement_type": "CITY",
        "settlement_id": "a0542042-87bd-4677-82bc-4ccb6fe67ce5",
        "settlement": "БЛАГОДАТНЕ",
        "country": "UA",
        "building": "15",
        "area": "ВОЛИНСЬКА",
        "apartment": "23"
      }
    ]
  }
}
```

and
`Get Legal Entities for another legal_entity` - correct

request
```
GET /api/legal_entities HTTP/1.1
Host: dev.ehealth.world
Authorization: Bearer RWFHNkF6RTRPOGdvd3V4TlgwWStXQT09
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 4a020561-e8cd-0089-121c-f88542c130e2
```

response
```
{
  "paging": {
    "size": null,
    "limit": 50,
    "has_more": false,
    "cursors": {
      "starting_after": null,
      "ending_before": null
    }
  },
  "meta": {
    "url": "http://dev.ehealth.world/api/legal_entities",
    "type": "list",
    "request_id": "6qpgp1jlabdb3rtkavvm5loseqtpgcdq",
    "code": 200
  },
  "data": []
}
```

**Comment by PavelVesnin** [comment]
@mmiliaieva @TarasenkoA fixed

**Comment by TarasenkoA** [comment]
work correctly
for request:
Get Legal Entities for another legal_entity and client empty in mitril - code 401
Get Legal Entities for another legal_entity with token is able to handle - 200 and no data in response
Get Legal Entity by ID for another legal_entity and client empty in mitril - code 401
Get Legal Entity by ID for another legal_entity with token is able to handle - code 403
