### ISSUE TITLE
Add search parameters in Get Empoyees List

### ISSUE THREAD

**Issue by mmiliaieva** [Nebo15/ehealth.api#515]
AS NHS admin I want search Employees by tax_id, edrpou and legal_entity_id
See [spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/employees/get-employees-list)

**Comment by TarasenkoA** [comment]
For parametr "legal_entity_id" incorrectly work filtration (show all info from db):

GET /api/employees?legal_entity_id=5dd314df-bf95-4359-b91e-f5f04deb3bd4 HTTP/1.1
Host: dev.ehealth.world
Content-Type: application/json
Authorization: Bearer SlQreWF5TXBza0dwU0RTS3phY0tUUT09
Cache-Control: no-cache
Postman-Token: c7add2c2-1fcd-84af-bbb8-3b4dc8e2c300

**Comment by TarasenkoA** [comment]
Ok.
Search Employees by tax_id, edrpou and legal_entity_id - work correctly.
