### ISSUE TITLE
Change Search MPI method

### ISSUE THREAD

**Issue by DPashchenko** [Nebo15/ehealth.api#528]
Process: Create declaration request
Step: [Search MPI](https://edenlab.atlassian.net/wiki/display/EH/IL.Create+declaration+request#IL.Createdeclarationrequest-SearchMPI)
- [ ] Add second_name parameter in Search MPI method.
- [ ] Remove phone_number parameter in Search MPI method.

**Comment by gmile** [comment]
Done in #555
