### ISSUE TITLE
Add mis_verified, nhs_verified in Get Legal Entities

### ISSUE THREAD

**Issue by mmiliaieva** [Nebo15/ehealth.api#540]
1. Add mis_verified, nhs_verified in Get Legal Entities
See API [spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/get-legal-entities)
2. Check that list consist of only legal entities with is_active = true

**Comment by mmiliaieva** [comment]
Approved
@TarasenkoA  will add tests in Postman

**Comment by TarasenkoA** [comment]
Added test in postman - "Get Legal Entities for NHS Admin" and tested
