### ISSUE TITLE
Add logic to URL generation

### ISSUE THREAD

**Issue by DPashchenko** [Nebo15/ehealth.api#595]
Method: POST declaration_requests
Step: Generate URL for documents
Add logic:
If `$.declaration_request.person.tax_id` not null:
* Generate URL with type `person.SSN`

For each `$.declaration_request.person.documents`:
* Generate URL's with type `person.{$.declaration_request.person.documents.[:].type}`

If `$.declaration_request.person.confidant_person.[:].tax_id` not null, for each:
* Generate URL with type `confidant_person.{confidant_person.type}.SSN`

For each `$.declaration_request.person.confidant_person.[:].documents_person`:
* Generate URL's with type `confidant_person.{confidant_person.type}.{$.declaration_request.person.confidant_person.[:].documents_person.[:].type}`

For each `$.declaration_request.person.confidant_person.[:].documents_relationship`:
* Generate URL's with type `confidant_person.{confidant_person.type}.{$.declaration_request.person.confidant_person.[:].documents_relationship.[:].type}`

**Comment by gmile** [comment]
Done in 9db5b5896f5b9a489143f64dd4338cb2b260546b and 38a82d19199e0cf7daa2713e1b16748d9cf5a56c. Available starting version 0.3.99, which is already deployed
