### ISSUE TITLE
Get declaration details by id

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#607]
As a doctor/owner/NHS admin
I want to be able to get declaration details
so that I can see who whot and with whom has signed

[spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/declarations-tbd/get-declaration-by-id)

acceptance criteria:
- [x] public endpoint returns 200 and data
- [x] doctor/owner can get access only to the declarations of his MSP
- [x] NHS admin can get all the declarations

**Comment by TarasenkoA** [comment]
In response i haven't information about status declaration and scope (line 101 and 102 in spec.)

**Comment by PavelVesnin** [comment]
@TarasenkoA fields added

**Comment by TarasenkoA** [comment]
pass
