### ISSUE TITLE
Deployment to demo

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#612]
Up DEMO to the version of DEV:
- [x] define required versions of repo to the destination env.
- [x] apply the required versions of repo to the destination env.
  - [x] ehealth.api
  - [x] prm.api
  - [x] mpi.api
  - [x] annon
  - [x] ael_api
  - [x] digital_signature_api
  - [x] man_api
  - [x] mithril_api
  - [x] ops
  - [x] uaddresses
  - [x] otp_verification_api
  - [x] nhs.auth.web
- [x] IL.dictionaries - add/update if any. IDs should be the same.
- [x] PRM.global_parameters - add/update if any. IDs should be the same
- [x] ~uaddresses - add/update records if any. IDs should be the same~
- [x] Migrate MAN templates from dev to demo DB,
- [x] GW.apis - migrate config
  - [x] in git
  - [ ] in db
  - [ ] GW.apis / GW.plugins - Exclude temp dev routes
- [ ] Mithril config
  - [x] client_types - add/update if any changes.
  - [x] roles - add/update if any changes.
  - [x] ~tokens - generate new tokens with new scopes in case if new endpoints are released~ won't happen, see below comment about Mithril,
  - [x] ~approvals - generate or copy MIS approvals~ won't happen, see below,
- [x] <s>man templates - no changes</s> actually there are changes, e.g. new declaration request form is added (look for `man` below)

**Comment by lymychp** [comment]
@AlekzandrV @gmile FYI

**Comment by gmile** [comment]
The following versions will make it into demo:

* ehealth.api – 0.3.123
* prm.api – 0.2.39
* mpi.api – 0.0.19
* annon – 0.11.5
* ael_api – 0.1.7
* digital_signature_api – 0.1.7
* man_api – 0.1.34
* mithril_api – 0.1.91
* ops – 0.1.8
* uaddresses – 0.1.17
* otp_verification_api – 0.1.13
* nhs.auth.web – 0.2.5

**Comment by gmile** [comment]
Dictionaries *match*:

* on dev:

```
il=# select name from dictionaries;
          name
-------------------------
 SCOPES
 LEGAL_FORM
 COUNTRY
 DIVISION_TYPE
 SPECIALITY_LEVEL
 EMPLOYEE_TYPE
 DOCUMENT_TYPE
 POSITION
 EDUCATION_DEGREE
 ADDRESS_TYPE
 LEGAL_ENTITY_STATUS
 GENDER
 PHONE_TYPE
 TERM_UNIT
 EMPLOYEE_REQUEST_STATUS
 QUALIFICATION_TYPE
 OWNER_PROPERTY_TYPE
 LEGAL_ENTITY_TYPE
 EMPLOYEE_STATUS
 SPECIALITY_TYPE
 SETTLEMENT_TYPE
 AUTHENTICATION_METHOD
 STREET_TYPE
 ACCREDITATION_CATEGORY
 KVEDS
 KVEDS_ALLOWED
(26 rows)

il=#
```

* on demo:

```
h-psql il ehealth-demo
psql (9.6.3)
Type "help" for help.

il=# select name from dictionaries;
          name
-------------------------
 SCOPES
 LEGAL_FORM
 COUNTRY
 DIVISION_TYPE
 SPECIALITY_LEVEL
 EMPLOYEE_TYPE
 DOCUMENT_TYPE
 POSITION
 EDUCATION_DEGREE
 ADDRESS_TYPE
 LEGAL_ENTITY_STATUS
 GENDER
 PHONE_TYPE
 TERM_UNIT
 EMPLOYEE_REQUEST_STATUS
 QUALIFICATION_TYPE
 OWNER_PROPERTY_TYPE
 LEGAL_ENTITY_TYPE
 EMPLOYEE_STATUS
 SPECIALITY_TYPE
 SETTLEMENT_TYPE
 AUTHENTICATION_METHOD
 STREET_TYPE
 ACCREDITATION_CATEGORY
 KVEDS
 KVEDS_ALLOWED
(26 rows)
```

**Comment by gmile** [comment]
* on dev:

```
prm=# select parameter, value from global_parameters;
           parameter            | value
--------------------------------+-------
 declaration_term               | 1
 declaration_request_term       | 1
 employ_request_term            | 30
 verification_request_term      | 3
 adult_age                      | 18
 billing_date                   | 2
 declaration_term_unit          | YEARS
 declaration_request_term_unit  | DAYS
 employ_request_term_unit       | DAYS
 verification_request_term_unit | DAYS
(10 rows)
```

* on demo:

```
prm=# select parameter, value from global_parameters;
 parameter | value
-----------+-------
(0 rows)

prm=#
```

It's empty. I'm going to add the records in demo DB.

**Comment by gmile** [comment]
- [x] <s>uaddresses - add/update records if any. IDs should be the same</s>

Did not check uaddresses since this was striken through.

**Comment by gmile** [comment]
- [x] Migrate MAN templates from dev to demo DB

* dev:
```
kubectl exec db-0 --context ehealth-dev --namespace man --stdin=true --tty=true -- psql --dbname man --username db -c 'select id, title from templates'
 id |                   title
----+--------------------------------------------
 34 | Test template
  2 | Employee registration success notification
  1 | Invitation email
  4 | DRPF
(4 rows)
```

* demo:
```
kubectl exec db-0 --context ehealth-demo --namespace man --stdin=true --tty=true -- psql --dbname man --username db -c 'select id, title from templates'
 id |                   title
----+--------------------------------------------
  2 | Employee registration success notification
  1 | Invitation email
 34 | Test template
  4 | DRPF
(4 rows)
```

**Comment by gmile** [comment]
- [x] GW.apis - migrate config

Done in: https://github.com/Nebo15/ehealth.k8s/commit/6c986729ec227728f40f2953c09a2e957413dc72#commitcomment-23092628

**Comment by gmile** [comment]
- [ ] Mithril config
  - [ ] client_types - add/update if any changes.
  - [ ] roles - add/update if any changes.
  - [x] ~tokens - generate new tokens with new scopes in case if new endpoints are released~ not applicable; all existing tokens should just work. all new tokens should receive proper scopes upon token generation
  - [x] ~approvals - generate or copy MIS approvals~; not applicable

**Comment by gmile** [comment]
Also did this – **we need to do this on prod during production data migration**:

- [x] update `MIS` and `MSP` client types with `app:authorize`

**Comment by vsirius** [comment]
done
