### ISSUE TITLE
[PRM] Create employee

### ISSUE THREAD

**Issue by mmiliaieva** [Nebo15/ehealth.api#63]
Implement the subj. service according to the [spec](http://docs.ehealthapi1.apiary.io/#reference/internal.-partner-relationship-management/employees/create-employee)
Basic [logic](https://edenlab.atlassian.net/wiki/pages/viewpage.action?pageId=1316436)

**Comment by lymychp** [comment]
Agreed with @mmiliaieva to reject and implement all the orchestration on the IL level.
