### ISSUE TITLE
Change search pending declaration requests method

### ISSUE THREAD

**Issue by DPashchenko** [Nebo15/ehealth.api#630]
Method: Create declaration request
Step: [Search pending declaration requests](https://edenlab.atlassian.net/wiki/display/EH/IL.Create+declaration+request#IL.Createdeclarationrequest-Searchpendingdeclarationrequests)
AS IS:
```
WHERE IL_DB.declaration_requests.data.declaration_request.person.tax_id = :($.declaration_request.person.tax_id)  
AND IL_DB.declaration_requests.data.declaration_request.employee_id = :($.declaration_request.employee_id)  
AND IL_DB.declaration_requests.data.declaration_request.legal_entity_id = :($.declaration_request.legal_entity_id)  
AND IL_DB.declaration_requests.status IN ('NEW', 'APPROVED')
```
TO BE:
Check `$.declaration_request.person.tax_id`
- [x] If exist:
```
WHERE IL_DB.declaration_requests.data.declaration_request.person.tax_id = :($.declaration_request.person.tax_id)  
AND IL_DB.declaration_requests.data.declaration_request.legal_entity_id = :($.declaration_request.legal_entity_id)  
AND IL_DB.declaration_requests.status IN ('NEW', 'APPROVED')
```
- [x] Else: move to next step

**Comment by gmile** [comment]
@TarasenkoA here we are effectively making 2 changes:

1. **remove employee_id** from searching pending declarations,
2. add condition to pending declaration deactivate:
    * if a `tax_id` is set on a person – proceed with deactivation,
    * if `tax_id` is missing from person (which is possible due to persons religious views) – **proceed without deactivation**.

Correct? If so, I'm ready to start working on the change.

**Comment by gmile** [comment]
Per discussion with @DPashchenko in person, the requirement can be reduced to the following:

> in case `tax_id` is absent, do not rely on tax_id when searching for pending declaration requests.
