### ISSUE TITLE
Add audit log for Repo.update_all()

### ISSUE THREAD

**Issue by PavelVesnin** [Nebo15/ehealth.api#638]
Add logging data changes for `Ecto.update_all()`.

Transaction steps:
1. Select data by update query
2. Map changes
3. Update entities
4. Insert audit log

**Comment by gmile** [comment]
@PavelVesnin after recent discussions (e.g. eventually deprecate the use of [ecto_trail](https://github.com/Nebo15/ecto_trail)), do we still need this?

This is what was discussed:
1. ecto_trail is too limited and will not cover arbitrary DB inserts / updates,
2. as a stepping stone, all further inserts / updates to DB must use Multi,
3. ultimately we'll try to rely on PG-level solution brought by @AlexKovalevych and described in https://wiki.postgresql.org/wiki/Audit_trigger.
