### ISSUE TITLE
audit_log in ops_db

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#644]
As a NHS
I want all the changes in the declarations table to be logged in the `audit_log` table
So that I can back-track who when and what has changed

**Comment by PavelVesnin** [comment]
@lymychp Ecto.Trail doesn't support transaction and bulk update operations. Here is the [ticket](https://github.com/Nebo15/ehealth.api/issues/638) for implementation this features

**Comment by gmile** [comment]
Status:

* writing changes to audit_log during declaration termination was done in https://github.com/Nebo15/ops.api/pull/7
* writing all declaration status changes was done in https://github.com/Nebo15/ops.api/pull/8
