### ISSUE TITLE
Declaration verification endpoints

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#674]
As a NHS admin 
I want to be able to verify or reject declarations that are pending_verification
So that I can keep updated information about the declaration status.

- [x] verify declaration endpoint
  * [specs](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/declarations-tbd/verify-declaration)
  * [service logic](https://edenlab.atlassian.net/wiki/display/EH/IL.Verify+declaration)
- [x] reject declaration endpoint 
  * [specs](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/declarations-tbd/reject-declaration)
  * [service logic](https://edenlab.atlassian.net/wiki/display/EH/IL.+Reject+Declaration)

**Comment by gmile** [comment]
Done. Will configure gateway now...

**Comment by gmile** [comment]
This is done and deployed on dev. @TarasenkoA please, put this in your test queue.

**Comment by gmile** [comment]
@TarasenkoA @lymychp routes were added in https://github.com/Nebo15/ehealth.k8s/commit/f15864cb1eea49a6582dcb87c96fc560dc227b6c
