### ISSUE TITLE
[IL] Create legal entity

### ISSUE THREAD

**Issue by mmiliaieva** [Nebo15/ehealth.api#76]
Implement the subj. service according to the [spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities)
Basic [logic](https://edenlab.atlassian.net/wiki/display/EH/IL.Create+Legal+Entity)

Copy https://github.com/Nebo15/prm.api/issues/83

**Comment by PavelVesnin** [comment]
[Done](https://github.com/Nebo15/prm.api/issues/83)
