### ISSUE TITLE
License entity: field requirement is not specified

### ISSUE THREAD

**Issue by gmile** [Nebo15/ehealth.api#8]
In `Licence` entity, are these fields optional or required?

> issued_date: 2017-02-28
> expiry_date: 2017-02-28

https://github.com/Nebo15/ehealth.api/blob/master/apiary.apib#L842-L843

The semantics suggests they _should_ be mandatory. But I need someone to confirm / deny this.

**Updated.** Same goes to [accreditation](https://github.com/Nebo15/ehealth.api/blob/master/apiary.apib#L835-L836).

**Comment by gmile** [comment]
@lymychp please, take a look

**Comment by gmile** [comment]
@AndrewDryga a meta note: looks like I cannot assign @lymychp to this ticket via GitHub. Is this intentional?

**Comment by AndrewDryga** [comment]
@gmile fixed, forgot to add their group to this repo.

**Comment by lymychp** [comment]
> issued_date: 2017-02-28 (string, required)
> expiry_date: 2017-02-28 (string, optional)

**Comment by gmile** [comment]
Fixed in https://github.com/Nebo15/ehealth.api/pull/9
