### ISSUE TITLE
[IL] Approve declaration request

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/ehealth.api#86]
### High-level overview

* [Apiary API](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/declaration-requests/approve-declaration-request)
* [Confluence spec](https://edenlab.atlassian.net/wiki/display/EH/IL.Approve+declaration+request)

### Trivia

* all actions that need to be taken specifically on IL are marked with bold.

### Configure gateway

  - [x] expose `approve declaration` public API endpoint,
  - [x] add proxy plugin to gateway, proxying all PATCH requests to `api-svc.il`,
  - [x] add acl plugin to gateway, with `declaration_request:write` scope required for `PATCH` (**_authorize user_**),
  - [x] add auth plugin to gateway, with common configuration (**_authorize user_**),
  - [x] add validation plugin to gateway, with JSON Schema set to schema from confluence (**_validate request_**).

### Get declaration request details

  - [x] read declaration request by id:
    ```sql
    SELECT *
    FROM IL_DB.declaration_request
    WHERE id = {Request.ID};
    ```
### Determine authorization method
  - [x] Case IL_DB.declaration_request.authentication_method
    - [x] IN ('OTP', 'OTP_TRUSTEE')
      - [ ] call **Verify code**
    - [x] = 'OFFLINE'
      - [x] call **Check uploaded documents**
    - [x] DEFAULT
      - [ ] error 424 (Failed Dependency)
      ```
      {
      "error": "Authentication method value is not matched."
      }
      ```
### Verify code
  - [ ] implement `complete OTP verification` microservice:
    - [x] implement an HTTP endpoint,
  - [x] ensure that `complete OTP verification` is deployed & properly configured in cluster,
    - [x] the service is deployed in cluster with name: @gmile 
    - [x] the service & required endpoint are working. To test it, call from a pod in cluster: @gmile 

### OLD
Implement the subj. service according to the [spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/declaration-requests/approve-declaration-request). Basic [logic](https://edenlab.atlassian.net/wiki/display/EH/IL.Approve+declaration+request).

**Comment by lymychp** [comment]
- [ ] test 5 sp

**Comment by gmile** [comment]
This is mostly done in #508

**Comment by lymychp** [comment]
@gmile please close if done

**Comment by gmile** [comment]
For the record, after quickly reviewing the steps described here, we don't have `OTP_TRUSTEE` per https://edenlab.atlassian.net/wiki/display/EH/IL.Create+declaration+request so `OTP_TRUSTEE` is not used.
