### ISSUE TITLE
[IL] Deactivate Employee

### ISSUE THREAD

**Issue by mmiliaieva** [Nebo15/ehealth.api#89]
Implement the subj. service according to the [spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/employees/deactivate-employee-tbd)
Basic [logic](https://edenlab.atlassian.net/wiki/display/EH/IL.Update+Employee)

**Comment by mmiliaieva** [comment]
I can not generate token
/oauth/apps/authorize repond with 401 error

**Comment by mmiliaieva** [comment]
New process logic #532

**Comment by mmiliaieva** [comment]
When the employee is deactivated, the role in mithril must be removed.
Example: employee_id = 98a78eca-5fd5-4109-b8f9-1ed45ef0d018

**Comment by mmiliaieva** [comment]
Change please error code for conflict transition on 409 with description
`  "error": {
    "type": "request_conflict",
    "message": "Employee is DEACTIVATED and cannot be updated"
  }`

Thanks

**Comment by mmiliaieva** [comment]
Role is not deleted from mithril
user_id = '3ccaf9fa-030c-4916-8aa6-5b730df73143'

**Comment by mmiliaieva** [comment]
Error code for conflict transition is OK:)

**Comment by PavelVesnin** [comment]
I'm trying to debug this method, so I get next credentials:
```
{
    "x-consumer-id": "6174b36b-abe8-426c-bb2d-ea76d469d71e", # Mithril token
    "client_id": "9c81824b-bc13-4d07-bc76-b069e2a2876b", # Mithril token
    "party_id": "f455656c-2deb-4874-8067-3a5104fe0b7f", # employee.party_id
    "user_id": "595ae654-9aa4-48ae-a58b-69ea4154c902" # party_users by party_id
  }
```
@mmiliaieva How did you get `3ccaf9fa-030c-4916-8aa6-5b730df73143` user_id?

**Comment by PavelVesnin** [comment]
@mmiliaieva fixed, deployed and tested on dev.
Tokens, apps and user roles was deleted for user `3ccaf9fa-030c-4916-8aa6-5b730df73143`

**Comment by mmiliaieva** [comment]
@PavelVesnin Role ADMIN is not deleted from mithril
user_id = 73010bc4-ce98-4298-8b04-ab0d96025d42

**Comment by TarasenkoA** [comment]
When i send `Deactivate Employee Owner` request - have error:
request
```
curl -X PATCH \
  http://dev.ehealth.world/api/employees/5a1477b0-b037-479a-9fb7-12d46e750b63/actions/deactivate \
  -H 'authorization: Bearer MUtMYm01UTBKN1BhT3RpdVY4aVR1Zz09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 63ea8d19-864d-238d-62f8-d2569788264b'
```
responce:
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/employees/5a1477b0-b037-479a-9fb7-12d46e750b63/actions/deactivate",
        "type": "object",
        "request_id": "jesaf057ib0eo5nkcibrhub4jdfvtdup",
        "code": 403
    },
    "error": {
        "type": "forbidden",
        "message": "You are not authorized or your token can not be resolved to scope"
    }
}
```

for request `Deactivate Employee Doctor` have error:

request:
```
curl -X PATCH \
  http://dev.ehealth.world/api/employees/aba211b1-f861-4226-a09c-33e73d1d3f35/actions/deactivate \
  -H 'authorization: Bearer MUtMYm01UTBKN1BhT3RpdVY4aVR1Zz09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 169458e7-37f8-6936-da7a-8ac49773a7f3'
```

responce:
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/employees/aba211b1-f861-4226-a09c-33e73d1d3f35/actions/deactivate",
        "type": "object",
        "request_id": "28oearbthrkl7ar39oumtn7404mf21vt",
        "code": 403
    },
    "error": {
        "type": "forbidden",
        "message": "You are not authorized or your token can not be resolved to scope"
    }
}
```

**Comment by AlekzandrV** [comment]
Tested - passed
