### ISSUE TITLE
[IL] Check phone number

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/ehealth.api#90]
### Implement Check phone service
  - [ ] service [specification](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/otp-verification-tdb/find-verifications-by-phone-number)

### Configure gateway

  - [x] expose `check phone number` public API endpoint,
  - [x] add proxy plugin to gateway, proxying all GET requests to `api-svc.il`,
  - [x] add acl plugin to gateway, with `otp:read` scope required for `GET` (**_authorize user_**),
  - [x] add auth plugin to gateway, with common configuration (**_authorize user_**).

**Comment by DPashchenko** [comment]
Create database model according to [specification](https://edenlab.atlassian.net/wiki/display/EH/Phone+number+verification)
Create service according to [specification](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/otp-verification/find-verifications-by-phone-number)

**Comment by lymychp** [comment]
- [ ] test 2 sp
