### ISSUE TITLE
[IL] Send verification code

### ISSUE THREAD

**Issue by AlekzandrV** [Nebo15/ehealth.api#91]
### Implement Generate OTP service
  - [ ] service [specification](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/otp-verification-tdb/initialize-otp-verification)

### Configure gateway

  - [x] expose `generate otp` public API endpoint,
  - [x] add proxy plugin to gateway, proxying all POST requests to `api-svc.il`,
  - [x] add acl plugin to gateway, with `otp:write` scope required for `POST` (**_authorize user_**),
  - [x] add auth plugin to gateway, with common configuration (**_authorize user_**).

**Comment by lymychp** [comment]
- [ ] use lifecell api to send sms in case if we have endpoint
